# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Domain\Bus\Query\QueryHandlerInterface:
            tags: ['internal.query_handler']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Domains/**/Infrastructure/**/Persistence/Doctrine/Entity/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Domain\Bus\Query\QueryBusInterface:
        class: App\Shared\Infrastructure\Bus\Query\InternalInMemoryQueryBus
        arguments: [!tagged_iterator 'internal.query_handler']
        tags: [ 'tagged_iterator_to_array' ]

    App\Domains\DeploymentFrequency\Domain\DeploymentRepositoryInterface:
        class: App\Domains\DeploymentFrequency\Infrastructure\Persistence\Doctrine\DoctrineDeploymentRepository

    App\Domains\DeploymentFrequency\Domain\FrequencyMetricRepositoryInterface:
        class: App\Domains\DeploymentFrequency\Infrastructure\Persistence\Doctrine\DoctrineFrequencyMetricRepository
